
```{r}
summary(cars)
```

You can also embed plots, for example:

```{r, echo=FALSE}
library(RMySQL)
library(tm)
library(SnowballC)
library(Matrix)
library(lda)
library(LDAvis)
library(servr)
library(fpc)
library(wordcloud)

subcases=NULL
mydb = dbConnect(MySQL(), user='root', password='', dbname='domainanalysis', host='localhost')
subcases<-dbGetQuery(mydb, "SELECT DISTINCT(Noun1_Count),Noun1 FROM `assetpartconditiondistribution` where equipmentType='GEN'")
#stopwordsList<-dbGetQuery(mydb, "SELECT stopword FROM `stopwordss`")
#domainWords<-dbGetQuery(mydb, "SELECT * FROM `domainwordss`")

#df[order(subcases$Noun1_Count)]

boxplot(subcases$Noun1_Count)
#take the words whose frency are above 1st quantile
df=subset(subcases,subcases$Noun1_Count>quantile(subcases$Noun1_Count,0.25))

#freqTable=sort(table(df$Noun1),decreasing = TRUE)
finalWordsForCloud=df$Noun1
finalWordsForCloud <- gsub(" ", "_", finalWordsForCloud)  # remove apostrophes

finalFreq=df$Noun1_Count
finalFreq


#create the datastructure of barplot
bb=finalFreq
names(bb)=finalWordsForCloud

plot.new()



#text(x=1,y=1,"STEAM_TURBINE")
barplot(sort(bb,decreasing = TRUE))




wordcloud(finalWordsForCloud, finalFreq,
            random.order = FALSE,
            colors=brewer.pal(8, "Dark2"),
            random.color=TRUE,
            max.words = 50,
            rot.per=.25,
            scale=c(4,.5)
            )
  
par(mfrow=c(1,1))







```
